version: '3.8'
services:
  db:
    image: postgres:15
    container_name: eav_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eav_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 
      - ./postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: eav_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
  migrate:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/eav_db -user=user -password=password migrate
    depends_on:
      - db